### ISSUE TITLE
Null Pointer Issue

### ISSUE THREAD

**Issue by spriyabalan** [camunda-consulting/migrate-to-camunda-tools#1]
Hi,
 I am trying to use the Pega to BPMN Convertor. I am using pega 8.4. I am getting below null pointer issue
Exception in thread "main" java.lang.NullPointerException
	at org.camunda.bpmn.generator.BPMNGenFromPega.main(BPMNGenFromPega.java:180)
Can you kindly help me to locate the issue

**Comment by superbeagle** [comment]
I'm pretty sure it's due to the fact that the converter does not yet cover all of the symbols in Pega yet. These are the XML tags of the covered symbols:

Data-MO-Event-Start
Data-MO-Activity-Assignment
Data-MO-Activity-SubProcess
Data-MO-Activity-Utility
Data-MO-Event-End
Data-MO-Event-Exception
Data-MO-Gateway-Decision 

Once we figure out what the missing symbol(s) is/are and the XML tag, it's literally a few lines of code to add. I could probably guess at the missing tags but I'd rather have actual examples. You can contact me directly at joe.pappas@camunda.com and we can set up a web conference to go through the xml to figure it out. Let me know. Thanks!

Joe

**Comment by superbeagle** [comment]
@spriyabalan any updates? You can search for 'pyShapeType' among the tags in your xmlto see if you have ones that don't match the above list

**Comment by superbeagle** [comment]
Hi @spriyabalan were you able to find the new tag?

**Comment by superbeagle** [comment]
No response back but will revisit if there is additional feedback

**Comment by spriyabalan** [comment]
Hi,
    Sorry for the late reply.  I was occupied with few other work. Based on
your inputs i will try and get back to you. Thanks & Regards

Regards,
Priya

**Comment by superbeagle** [comment]
No problem, reopening!

**Comment by superbeagle** [comment]
@spriyabalan are there any updates? Let me know, thanks.
